servers:
  endpoints:
    user:
      uri: "http://172.25.0.3:8081"
      path: "/user"
    auth:
      uri: "http://172.25.0.3:8081"
      path: "/auth"
    book:
      uri: "http://localhost:8082"
      path: "/book"
    review:
      uri: "http://localhost:8083"
      path: "/review"